Feature/translation bar
Crescent-Labs/iqra-android pull request #9
Opened 2016-11-26 15:31 UTC by hussain-alhomedawy

2016-12-05 05:28 UTC, mmmoussa commented
For the api request when changing translations on the results page, instead of performing a search, use the translations endpoint at `api/v3.0/translations`. Send a post request with the body containing the api key as `apikey` (same as search), the new translation short-code (eg. "en-hilali") as `translation` (same as search), and the ayahs to fetch a translation for as `ayahs`. `ayahs` should be an array of objects, with each object having a `surahNum` and `ayahNum` property. An example of a valid value for `ayahs` is: `[{"surahNum":2,"ayahNum":286},{"surahNum":65,"ayahNum":7}]`.

The response will look like this:
```
{
  "result": [
    {
      "ayahNum": 286, 
      "surahNum": 2, 
      "translationAyah": "Allah burdens not a person beyond his scope. He gets reward for that (good) which he has earned, and he is punished for that (evil) which he has earned. \"Our Lord! Punish us not if we forget or fall into error, our Lord! Lay not on us a burden like that which You did lay on those before us (Jews and Christians); our Lord! Put not on us a burden greater than we have strength to bear. Pardon us and grant us Forgiveness. Have mercy on us. You are our Maula (Patron, Suppor-ter and Protector, etc.) and give us victory over the disbelieving people."
    }, 
    {
      "ayahNum": 7, 
      "surahNum": 65, 
      "translationAyah": "Let the rich man spend according to his means, and the man whose resources are restricted, let him spend according to what Allah has given him. Allah puts no burden on any person beyond what He has given him. Allah will grant after hardship, ease."
    }
  ]
}
```

2016-12-27 18:42 UTC, mmmoussa requested changes

2016-12-27 18:42 UTC, mmmoussa commented on app/src/main/AndroidManifest.xml
> +        android:name="com.mmmoussa.iqra.AnalyticsApplication"
Why has the package name been added before all the names?

2016-12-27 18:42 UTC, mmmoussa commented on app/src/main/java/com/mmmoussa/iqra/SearchResultsActivity.java
> +            int numOfMatches = result.length();
The translations endpoint does not change the number of results, and so there's no need to update the displayed result count or to check if the results are <= 150. As a result, lines 257 to 271 can be deleted except for line 270.

2016-12-27 18:42 UTC, mmmoussa commented on app/src/main/java/com/mmmoussa/iqra/objects/Ayah.java
> +        this.translatedSurah = translatedSurah;
This should actually be `translatedSurahName` instead of `translatedSurah`.

2016-12-27 18:42 UTC, mmmoussa commented on app/src/main/res/layout/activity_search_results.xml
> +        android:layout_height="wrap_content"
This line is causing an issue with all searches that don't have enough results to fill the page. When you click a result to expand it, the expansion becomes confined to the original result size. Remove this line.

2016-12-28 17:13 UTC, hussain-alhomedawy commented on app/src/main/AndroidManifest.xml
> +        android:name="com.mmmoussa.iqra.AnalyticsApplication"
Discussed offline. Was a result of refactoring the package name

2016-12-28 17:49 UTC, hussain-alhomedawy commented
Thanks for the review @mmmoussa! Let me know if there's anything else

2016-12-29 01:18 UTC, mmmoussa approved these changes

2016-12-29 01:19 UTC, merged